### ISSUE TITLE
match OIDC identity to Django user issues

### ISSUE THREAD

**Issue by willkg** [mozilla/mozilla-django-oidc#102]
Right now, mozilla-django-oidc matches an OIDC identity to a Django user via the Django user email field.

That's problematic for a couple of reasons:

1. the code is doing a case-sensitive exact match, so it's possible that could fail if the case ever changes (email addresses on some systems are case-insensitive)
2. the email field in the Django user table is not marked as unique and thus you can have multiple Django users with the same email field

I think to fix item 1, we want to do a case-insensitive match even though technically, email addresses are case-sensitive.

I think to fix item 2, we want to be using the username field of the Django user table and not the email field. Django 1.11's username field works fine with that. It means we don't have to generate usernames from email addresses. It means two users can't have the same email address. It solves a bunch of things for us.

Are there other issues we need to work around?

Are there better ways to solve this?

**Comment by techdragon** [comment]
I'd like to recommend that any solution to this issue, provide a simple method for people using custom user models to override the behaviour meant for use with the default Django user model.

For instance one of the things I frequently do with a custom user model is mark the email address as unique in the database and case normalise to lowercase in order to ensure no uppercase/lowercase duplicates.

**Comment by willkg** [comment]
@techdragon It already allows for that.

https://mozilla-django-oidc.readthedocs.io/en/latest/installation.html#connecting-oidc-user-identities-to-django-users

I wrote up this issue to fix the default behavior.

**Comment by akatsoulas** [comment]
Having the email as the identifier is handy because of its use to login to a RP. That said, I think it makes sense to use Django's `username` and maybe we could give the ability to the users to change this behavior through the configuration of the lib.  If we are going down this way, I don't think that we should consider the case-sensitivity of the email an issue any more. 👍 for this change.

**Comment by willkg** [comment]
I'll throw together a PR to fix the case-sensitive check.

I'm on the fence about whether to move this to the username field because Django 1.8 and 1.9 have a username field has a 30 character maximum.

Part of me is thinking that we should wait to make that change until after we've dropped support for Django 1.8 and 1.9.

**Comment by tpazderka** [comment]
Would it be possible to create a mapping model connecting `sub` claim with `UserModel`?

Matching users by `sub` should be more safe and reliable than matching by `username` or `email`.

**Comment by willkg** [comment]
@tpazderka Can't you do that already? https://mozilla-django-oidc.readthedocs.io/en/latest/installation.html#connecting-oidc-user-identities-to-django-users

**Comment by tpazderka** [comment]
Not without adding the `sub` to your user model. What I had in mind is a model in mozilla-django-oidc that would keep the mapping between user and received sub.

**Comment by peterbe** [comment]
@tpazderka I *think* what you're proposing that mozilla-django-oidc adds a model that looks something like this:
```
class Sub2User(models.Model):
    sub = models.CharField(unique=True)
    user = models.ForeignKey('User') 
```
Then you can quickly turn the `sub` (from the claim) into a user. But it's **out of scope**. 

This issue is about finding that `User` instance in the first place. To do that there are a couple of things:

1. mozilla-django-oidc could do a better job matching by email (will is going to try to tackle the case-sensitivity part)
2. You still might have to write [your own `filter_users_by_claims`](https://mozilla-django-oidc.readthedocs.io/en/latest/installation.html#connecting-oidc-user-identities-to-django-users) as Will pointed out. 

Then, the next time you could do something like this:
```
sub = claims['sub']
try:
    return Sub2User.objects.get(sub=sub).user
except Sub2User.DoesNotExist:
    user = super().filter_users_by_claims(claims)
    Sub2User.objects.create(sub=sub, user=user)
    return user
```

Either way, it's something you might want to consider in your own implementation. 

And the code above (but done nicer) could be part of your own `filter_users_by_claims` subclass method.

**Comment by tpazderka** [comment]
@peterbe Yes, this is exactly what I had in mind. Issues with matching by email are multiple (the field can be blank and not unique) so I thought that adding `sub` as a default matching method in `OIDCAuthenticationBackend` would be a good generalization method.

But if you think it is out of scope, we will manage it in our own implementation.

**Comment by willkg** [comment]
@peterbe That makes sense to me and I think it covers my concerns. I'm going to close this out. If there are new issues that are "in real life" and less hypothetical, we can address them in a new issue.
