### ISSUE TITLE
Consider a name change?

### ISSUE THREAD

**Issue by peterbe** [mozilla/mozilla-django-oidc#107]
Having the word "mozilla" in the name implies (at least to me) that this is extremely Mozilla specific. But I think that's not true; it's Django and an OAuth2 provider, right? Nothing specific to Mozilla. 

At first I thought, why not just call it "django-oidc" but then I noticed this: https://github.com/mozilla/mozilla-django-oidc/issues/106

**Comment by akatsoulas** [comment]
That's true, although the usage initially was tightly tied to Mozilla. We implemented only the code flow and we tried to follow the BrowserId paradigm in order to easily plug it to existing projects. That said I am totally open to a name change and more than happy to augment the functionality so that we can have a complete OIDC lib. Any good suggestions about the name? @johngian thoughts?

**Comment by peterbe** [comment]
@willkg is good with names :)

**Comment by willkg** [comment]
As much as I want a generally useful library for everyone in the world, I don't really care that much. We have a lot of Django sites in Mozilla and it behooves us greatly to simplify everyone's situation with a library that caters to Mozilla sites as a primary use case. That's my opinion in case it's helpful.

I don't have any good name ideas offhand, but I can think about it. Having said that, I don't think of this as *my* project so much as it's a project I'm helping out on. So there's that.

**Comment by johngian** [comment]
I am also leaning towards facilitating our projects needs first but that doesn't mean that the library is tied to any special functionality that we use in our django projects. My suggestion is to focus to our own needs and keep custom (auth0) functionality under contrib, but not aim for a full OIDC implementation just for the sake of providing a fully compatible lib.

Also regarding names, ``mozilla-django-oidc`` was chosen because when we started building this we were in the process of learning about OIDC and the Auth0 service and we were not sure if the outcome could be something that could be used by others or if its something internal.

That said, I am open to changing the project's name.

What we initially aimed for was to have a lightweight lib that

* Doesn't do magic on user filtering/creation
* Doesn't store all OIDC data in the DB
* Allow devs to override a couple of methods or even completely extend the authentication backend for custom functionality

So what about something related to ``light`` or ``lite``? For example ``django-lite-oidc``?

**Comment by peterbe** [comment]
Feel like it's too late now anyway.
