### ISSUE TITLE
response_type is hard coded

### ISSUE THREAD

**Issue by h4ppysmile** [mozilla/mozilla-django-oidc#295]
my client response type to work needs to be `id_token token`  but it is hard coded `code` at line 143 of `views.py` . 
Is not better to make it config?

**Comment by bjornuppeke** [comment]
I actually have the exact same issue. But after reading up on it a bit I found that there is actually a lot more to it than just changing the `response_type`. If you do so you are telling the Provider that you are using a whole different `flow`. `response_type=code` uses the 'authorization code flow' which means that the client needs to make 2 requests to get the token:

1. First request the `authorization` endpoint to retrieve an `Authorization code`. This is what happens in the 2 `views` in this package.
2. Then use the `code` you get and request the `Token` endpoint to retrieve the `ID Token` and `Access token`. This is handled in the `auth` backend which the view calls from here: [View.get](https://github.com/mozilla/mozilla-django-oidc/blob/master/mozilla_django_oidc/views.py#L91) => [AuthBackend.authenticate](https://github.com/mozilla/mozilla-django-oidc/blob/master/mozilla_django_oidc/auth.py#L274) => [AuthBackend.get_token](https://github.com/mozilla/mozilla-django-oidc/blob/master/mozilla_django_oidc/auth.py#L224)

Good explanation of the flows here: https://medium.com/@darutk/diagrams-of-all-the-openid-connect-flows-6968e3990660

This package is (from what I understand) basically built to only follow the `authorization code flow`.

If you want to set `response_type` to `id_token token` (which uses the `implicit flow`) you would need to implement your own `AuthBackend`. Extend the `OIDCAuthenticationBackend` and implement a new `authenticate` method. Since the initial authorization endpoint callback request will contain the `ID Token` (given your Provider is implemented according to specs) you can skip getting the token and just go on [verifying the token](https://github.com/mozilla/mozilla-django-oidc/blob/master/mozilla_django_oidc/auth.py#L279).

Thats how I intend on solving it anyway!

**Comment by johngian** [comment]
The scope of this library is to support only authorization code flow. I don't thing we are planning to handle other OIDC flows any time soon because this implies a lot of work on how we handle authentication. Thanks for the feedback :rocket:
