### ISSUE TITLE
Make 'state' optional in authentication request.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/mozilla-django-oidc#45]

**Comment by gdestuynder** [comment]
i do not think this is needed anymore, see https://github.com/mozilla-iam/auth0-deploy/commit/e3e261a70653dd9701138455d0dc4fa707cc0563#diff-d1b26f3c70508e6f65750cdc305e0ce5R282 for state support with passwordless.

that said, i would recommend using the hosted lock instead of hard coding a different one, it already has the fixes

**Comment by willkg** [comment]
Can this one be closed out? If not, what needs to be done here?

**Comment by johngian** [comment]
Yes let's close this. It was opened as a workaround to fix hosted vs modal lock back then.
