### ISSUE TITLE
Add support for offline develpment in the lib. 

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/mozilla-django-oidc#63]

**Comment by willkg** [comment]
I was trying to figure this out when I wrote the auth0 stuff for Standup.

Any thoughts on how to approach this?

**Comment by akatsoulas** [comment]
Not really, at least not a good one. Maybe we could have a test app that would use github as provider? Ideas more than welcome!

**Comment by johngian** [comment]
What if we mock the OIDC API calls?

**Comment by willkg** [comment]
I think if I had my druthers, I'd have two things:

1. A mock for this library that let developers test authentication flows so they can write tests for their site that cover "what happens if the user doesn't exist?", "what happens if the user exists, but is disabled?", "what happens if the user claim data looks like this?", etc. Testing authentication flows is a pain in the ass. A mock would make that a lot easier even if it only covered a few scenarios.
2. A fake OIDC server that I could run in a Docker container and point my site at for local development. It'd implement the various API endpoints that we use. It'd need to allow me to specify user data it should use so that I could test the various flows.

Towards the first, I've written a bunch of mocking libraries. If we're using requests, then we could make it a request adapter that covers very specific urls. I think I could bang out something along those lines in a day or two.

Towards the second, I was looking at http://django-oidc-provider.readthedocs.io/en/v0.4.x/ which would either work or provide a starting point or provide inspiration for throwing something together, maybe? I'm not sure what other options there are.

Maybe we could go the moto route, write a mock, and then wrap that in a server that can run in a Docker container?

Does that sound plausible? If so, then I'll try to find some time to explore it further this month.

**Comment by willkg** [comment]
I'm going to spin off the "add a mock" to a new issue. I really think that's worth exploring further and probably "easy" to do.

**Comment by johngian** [comment]
I gave a ``docker-compose`` based setup a run here #205 
You can find more information in ``README``.

Closing this for now. Let's reopen it in the future if the setup needs more work.
